version: '3'

networks:
  node-net-rocks:
    driver: bridge

services:
  
  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    volumes:
      - ./db_data/:/var/lib/mysql
      - ./db_dump/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-net-rocks
#mysql -uroot -proot
#&& 
#              mysql -uroot -proot
#              && use nodedb;
#              && source /usr/temp/create_tables.sql