version: '3'

networks:
  node-net-rocks:
    driver: bridge

services:
  
  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    volumes:
      - ./db_data/:/var/lib/mysql
      - ./db_dump/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-net-rocks
  
  app:
    build: 
      context: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s docker-entrypoint.sh
    command: ["node", "index.js"]
    restart: always
    depends_on:
      - mysql
    networks:
      - node-net-rocks
    tty: true 

  nginx:
    build: 
      context: ./nginx
      dockerfile: dockerfile.prod
    image: werinton/nginx:prod
    container_name: nginx
    depends_on:
      - app
    restart: always
    networks:
      - node-net-rocks
    ports:
      - "8080:80"
